steps:
  # Build the API image
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'gcr.io/$PROJECT_ID/ecommerce-api:latest', '-f', 'docker/Dockerfile.api', 'server']
  
  # Build the client image
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'gcr.io/$PROJECT_ID/ecommerce-client:latest', '-f', 'docker/Dockerfile.client', 'client']
  
  # Push the API image
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/$PROJECT_ID/ecommerce-api:latest']
  
  # Push the client image
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/$PROJECT_ID/ecommerce-client:latest']
  
  # Deploy API to Cloud Run
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: gcloud
    args:
      - 'run'
      - 'deploy'
      - 'ecommerce-api'
      - '--image'
      - 'gcr.io/$PROJECT_ID/ecommerce-api:latest'
      - '--region'
      - 'us-central1'
      - '--platform'
      - 'managed'
      - '--allow-unauthenticated'
      - '--port'
      - '8080'
      - '--memory'
      - '512Mi'
      - '--cpu'
      - '1'
      - '--max-instances'
      - '10'
      - '--set-env-vars'
      - 'NODE_ENV=production,DB_HOST=${_DB_HOST},DB_NAME=${_DB_NAME},DB_USER=${_DB_USER},DB_PASSWORD=${_DB_PASSWORD},JWT_SECRET=${_JWT_SECRET},GCP_PROJECT_ID=${_GCP_PROJECT_ID},GCP_BUCKET_NAME=${_GCP_BUCKET_NAME}'
  
  # Deploy client to Cloud Run
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: gcloud
    args:
      - 'run'
      - 'deploy'
      - 'ecommerce-client'
      - '--image'
      - 'gcr.io/$PROJECT_ID/ecommerce-client:latest'
      - '--region'
      - 'us-central1'
      - '--platform'
      - 'managed'
      - '--allow-unauthenticated'
      - '--port'
      - '8080'
      - '--memory'
      - '256Mi'
      - '--cpu'
      - '1'
      - '--max-instances'
      - '5'
      - '--set-env-vars'
      - 'REACT_APP_API_URL=${_API_URL},REACT_APP_ENVIRONMENT=production'

images:
  - 'gcr.io/$PROJECT_ID/ecommerce-api:latest'
  - 'gcr.io/$PROJECT_ID/ecommerce-client:latest'

substitutions:
  _DB_HOST: '34.63.40.75'
  _DB_NAME: 'ecommerce_db'
  _DB_USER: 'ecommerce_user'
  _DB_PASSWORD: '8779700241'
  _JWT_SECRET: 'your-super-secret-jwt-key-change-in-production'
  _GCP_PROJECT_ID: 'ecommerce-466322'
  _GCP_BUCKET_NAME: 'ecommerce-466322-ecommerce-media'
  _API_URL: 'https://ecommerce-api-259247630648.us-central1.run.app' 