version: '3.8'

services:
  # PostgreSQL Database
  postgres:
    image: postgres:15-alpine
    container_name: ecommerce_postgres
    environment:
      POSTGRES_DB: ecommerce_db
      POSTGRES_USER: ecommerce_user
      POSTGRES_PASSWORD: 8779700241
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - ecommerce_network
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ecommerce_user -d ecommerce_db"]
      interval: 10s
      timeout: 5s
      retries: 5

  # Redis
  redis:
    image: redis:7-alpine
    container_name: ecommerce_redis
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    networks:
      - ecommerce_network
    restart: unless-stopped

  # Backend API
  api:
    build:
      context: ../server
      dockerfile: ../docker/Dockerfile.api
    container_name: ecommerce_api
    environment:
      NODE_ENV: development
      PORT: 5000
      DB_HOST: 34.63.40.75
      DB_PORT: 5432
      DB_NAME: ecommerce_db
      DB_USER: ecommerce_user
      DB_PASSWORD: 8779700241
      REDIS_HOST: redis
      REDIS_PORT: 6379
      JWT_SECRET: 9bd117a27fe0c2b3b40823ebc51d0d91913901a3841cce82b3b9b19a78e1ca9359a364c61ba87b26f17180a8fa6689aa7ed979aeed4880b4292a1e8466e4b82c
      JWT_EXPIRES_IN: 10d
      RAZORPAY_KEY_ID: your_razorpay_key_id
      RAZORPAY_KEY_SECRET: your_razorpay_key_secret
      GCP_PROJECT_ID: ecommerce-466322
      GCP_BUCKET_NAME: ecommerce-466322-bucket
      GCP_KEY_FILE: /app/gcp-key.json
      CLIENT_URL: https://ecommerce-client-fnzcggriwq-uc.a.run.app
      RATE_LIMIT_WINDOW_MS: 900000
      RATE_LIMIT_MAX_REQUESTS: 100
    ports:
      - "5001:5000"
    volumes:
      - ../server:/app
      - /app/node_modules
      - ./gcp-key.json:/app/gcp-key.json:ro
    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_started
    networks:
      - ecommerce_network
    restart: unless-stopped

  # Frontend Client
  client:
    build:
      context: ../client
      dockerfile: ../docker/Dockerfile.client
    container_name: ecommerce_client
    environment:
      REACT_APP_API_URL: http://localhost:5001/api
      REACT_APP_ENVIRONMENT: production
    ports:
      - "3000:3000"
    volumes:
      - ../client:/app
      - /app/node_modules
    depends_on:
      - api
    networks:
      - ecommerce_network
    restart: unless-stopped

  # Nginx
  nginx:
    image: nginx:alpine
    container_name: ecommerce_nginx
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - ./ssl:/etc/nginx/ssl:ro
    depends_on:
      - api
      - client
    networks:
      - ecommerce_network
    restart: unless-stopped

  # Adminer (Optional)
  adminer:
    image: adminer:latest
    container_name: ecommerce_adminer
    environment:
      ADMINER_DEFAULT_SERVER: postgres
    ports:
      - "8080:8080"
    depends_on:
      - postgres
    networks:
      - ecommerce_network
    restart: unless-stopped

volumes:
  postgres_data:
  redis_data:

networks:
  ecommerce_network:
    driver: bridge
